name: examen_unidad2
description: "Proyecto Flutter con Clean Architecture (Reserva System)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  http: ^1.2.2

  get_it: ^9.0.5
  injectable: ^2.6.0

  shared_preferences: ^2.2.2

  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  fluttertoast: ^8.2.12
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.10.1
  injectable_generator: ^2.9.1

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
